'use client';
import {useEffect,useState} from 'react';
import '../../../admin/admin.css';
import './balance.css';

const money=(v:any)=>new Intl.NumberFormat('vi-VN').format(Number(v)||0)+'đ';
const moneyInput=(v:string)=>v?new Intl.NumberFormat('vi-VN').format(Number(v)):'';
export default function BalancePage({params}:{params:Promise<{id:string}>}){
 const [id,setId]=useState(''),[u,setU]=useState<any>(),[mode,setMode]=useState<'add'|'sub'>('add'),[amount,setAmount]=useState(''),[reason,setReason]=useState('Điều chỉnh thủ công'),[note,setNote]=useState(''),[msg,setMsg]=useState(''),[saving,setSaving]=useState(false);
 useEffect(()=>{params.then(p=>{setId(p.id);fetch('/api/admin/users').then(r=>r.json()).then(d=>setU((d.data||[]).find((x:any)=>x.id===p.id)))})},[params]);
 async function save(){const n=Number(amount);if(!n||n<0)return setMsg('Vui lòng nhập số tiền hợp lệ.');if(saving)return;setSaving(true);setMsg('');try{const r=await fetch('/api/admin/users',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,action:'balance',amount:mode==='add'?n:-n,reason,note})});const d=await r.json().catch(()=>({}));if(!r.ok){setMsg(d.error||'Không thể cập nhật số dư.');return}setU((current:any)=>({...current,balance:d.data.balance}));setAmount('');setNote('');setMsg(mode==='add'?'Đã cộng số dư thành công.':'Đã trừ số dư thành công.')}catch{setMsg('Không thể kết nối máy chủ. Vui lòng thử lại.')}finally{setSaving(false)}}
 if(!u)return <div className="admin-body">Đang tải dữ liệu...</div>;
 return <div className="admin-body balance-page"><p className="balance-crumb">Người dùng　›　Chi tiết người dùng　›　Cộng/Trừ số dư</p><button className="back-btn" onClick={()=>history.back()}>←　Quay lại</button><h2>Cộng/Trừ số dư</h2><p className="admin-only-sub">Điều chỉnh số dư tài khoản người dùng</p><section className="balance-user admin-card"><div className="balance-avatar">{u.username.slice(0,2).toUpperCase()}</div><div><h1>{u.username} <span className="pill blue">{u.role}</span></h1><p>{u.email}</p><small>Thành viên từ {new Date(u.createdAt).toLocaleDateString('vi-VN')}</small></div><Stat t="Số dư hiện tại" v={money(u.balance)}/><Stat t="Tổng đã nạp" v={money(u.totalDeposited)}/><Stat t="Tổng đơn hàng" v={u._count?.orders||0}/></section><section className="balance-grid"><div className="admin-card balance-form"><h2>♙　Điều chỉnh số dư</h2><p>Cộng hoặc trừ số dư cho tài khoản người dùng</p><div className="mode"><button className={mode==='add'?'selected add':''} onClick={()=>setMode('add')}>＋　Cộng số dư</button><button className={mode==='sub'?'selected sub':''} onClick={()=>setMode('sub')}>⊖　Trừ số dư</button></div><label>Số tiền cần {mode==='add'?'cộng':'trừ'}<input value={moneyInput(amount)} onChange={e=>setAmount(e.target.value.replace(/\D/g,''))} placeholder="Nhập số tiền..." inputMode="numeric" autoComplete="off"/><small>Số tiền sẽ được cập nhật trực tiếp vào số dư tài khoản</small></label><label>Lý do điều chỉnh<select value={reason} onChange={e=>setReason(e.target.value)}><option value="Điều chỉnh thủ công">Điều chỉnh thủ công</option><option value="Thưởng sự kiện">Thưởng sự kiện</option><option value="Hoàn tiền">Hoàn tiền</option><option value="Khác">Khác</option></select></label><label>Ghi chú (tùy chọn)<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Nhập ghi chú..."/></label><button className="save-balance" disabled={saving} onClick={save}>{saving?'Đang cập nhật...':mode==='add'?'＋ Cộng số dư cho người dùng':'⊖ Trừ số dư người dùng'}</button>{msg&&<p className="balance-msg">{msg}</p>}</div><aside className="admin-card user-info"><h2>♙　Thông tin người dùng</h2><p>ID　 {u.id}</p><p>Tên người dùng　 <b>{u.username}</b></p><p>Email　 {u.email}</p><p>Vai trò　 {u.role}</p><p>Số dư hiện tại　 <b>{money(u.balance)}</b></p><p>Tổng đã nạp　 {money(u.totalDeposited)}</p></aside></section></div>;
}
function Stat({t,v}:{t:string;v:any}){return <div className="balance-stat"><small>{t}</small><b>{v}</b></div>}
